title: rbleattler
subtitle: DevOps Engineer, Developer Advocate, Open Source Contributor, PowerShell Enthusiast
description: >- # this means to ignore newlines until the next key
  rbleattler's professional blog and other musings.

url: "https://rbleattler.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    # - text: Gallery #@ maybe reenable at some point. Not a bad idea
    #   url: /gallery
    # - text: Shop #@ maybe reenable at some point. Not a bad idea
      # url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Rob Bleattler
author_bio: Hi, my name is Rob Bleattler. I am a DevOps Engineer, Developer Advocate, Open Source Contributor, and PowerShell Enthusiast.
author_email: "rbleattler@gmail.com"
author_location: United States
author_website_url: "https://robertbleattler.com"
typewrite-text: I am a DevOps Engineer, developer advocate, open source contributor, and PowerShell enthusiast.
hero_cover_img: ghio_bg.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: FreedomPay
              company_logo: freedompay_logo.png
              company_url: https://freedompay.com
              designation: DevOps Engineer
              description: Championing the DevOps culture and practices at FreedomPay. I am responsible for improving developer productivity and efficiency through automation and tooling. I am also responsible for the reliability and availability of our production systems.
              visibility: true
            - company_name: United BioSource Corporation
              company_logo: UBC-logo.png
              company_url: https://ubc.com
              designation: Senior Manager of DevOps
              description: As the Senior Manager of DevOps at UBC I led an ongoing effort to establish the DevOps Center of Excellence. By driving the adoption of DevOps culture and practices, my team and I worked to strengthen agility, reliability, and security throughout the organization.
              visibility: true

# Education
author_education_details:
              - college_logo: peirce.png
                college_name: Peirce College
                college_url: https://peirce.edu
                college_degree: Information Technology
                description: Associate in Science
                visibility: false

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false

# social links
twitter_username: robertbleattler
github_username:  rbleattler
# facebook_username: 
linkedin_username: rbleattler
# behance_username: johndoe
instagram_username: rbleattler
medium_username: rbleattler
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe
# buyMeACoffee_username: rbleattler

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

disqus_shortname: rbleattlr
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: "@rbleattler"
# wakatime_languages_guid: dda068dc-9ef8-4c69-9e34-e6d2abb0eafb #Dark, 7 days
# wakatime_languages_guid: 9caf00a1-9057-4a6c-a711-3a5769746646 #Dark, All Time
# wakatime_activity_guid: e4a7f9a6-7e1d-4af4-8eac-26ba0033c8ac #Dark, 7 days
wakatime_languages_guid: 8e83d326-1068-4704-8ad5-b79ef9ef0930 #Transparent back, foreground Orange, All Time
wakatime_activity_guid: 1fc68152-8d28-4893-afc8-1aa6a0b33ec1 #Transparent, 7 days


# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://github.us8.list-manage.com/subscribe?u=c9157d9a7abc5ee3a586f8ec3&id=b316836bce

# contact form - (choose formspress or getform)
getform_endpoint: 5dd7f8bc-643b-490a-a171-ab348c35e347
# formspree_email: rbleattler+githubio@gmail.com

# releases - widget can be (sidebar, modal or embed)
# olvy_organization: coast-technologies
# olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
